/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_packagefile_free(a: number): void;
export function packagefile_new(a: number, b: number, c: number, d: number): number;
export function __wbg_themecolors_free(a: number): void;
export function themecolors_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function rgb_new(a: number, b: number, c: number): number;
export function __wbg_typststate_free(a: number): void;
export function __wbg_get_typststate_pt(a: number): number;
export function __wbg_set_typststate_pt(a: number, b: number): void;
export function __wbg_get_typststate_size(a: number): number;
export function __wbg_set_typststate_size(a: number, b: number): void;
export function __wbg_get_typststate_theme(a: number): number;
export function __wbg_set_typststate_theme(a: number, b: number): void;
export function __wbg_fileid_free(a: number): void;
export function typststate_new(): number;
export function typststate_insertFile(a: number, b: number, c: number, d: number, e: number): number;
export function typststate_installPackage(a: number, b: number, c: number, d: number, e: number): void;
export function typststate_sync(a: number, b: number, c: number, d: number): number;
export function typststate_click(a: number, b: number, c: number, d: number): number;
export function typststate_autocomplete(a: number, b: number, c: number, d: number): void;
export function typststate_resize(a: number, b: number, c: number, d: number, e: number): void;
export function __wbg_rgb_free(a: number): void;
export function start(): void;
export function qcms_profile_is_bogus(a: number): number;
export function qcms_white_point_sRGB(a: number): void;
export function qcms_profile_precache_output_transform(a: number): void;
export function qcms_transform_data_rgb_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgba_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_bgra_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgb_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgba_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_bgra_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_release(a: number): void;
export function qcms_enable_iccv4(): void;
export function lut_interp_linear16(a: number, b: number, c: number): number;
export function lut_inverse_interp16(a: number, b: number, c: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
