[workspace]
members = ["wasm", "tauri"]
package.authors = ["Lemuel DLS"]
package.categories = []
package.edition = "2021"
package.keywords = [""]
package.license = "Apache-2.0"
package.repository = "https://github.com/lemueldls/mnemo"
package.version = "0.1.0"
resolver = "2"

# [profile.release]
# codegen-units = 1
# lto = true

[profile.release.package."*"]
codegen-units = 1

[profile.bench]
codegen-units = 1
lto = true

[profile.bench.package."*"]
codegen-units = 1
