// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lOfOPOOOmOQO'#C`OQOPO'#CnOQOPO'#CqOOOO'#C_'#C_O{OSO'#C_OOOO'#Ct'#CtO!^OPO'#C^QOOOOOO{OSO'#CbOOOO'#Cb'#CbOOOO'#Cu'#CuO!hOQO,58zOOOO,58z,58zO!vOSO,59YO!{OWO,59]O#QOPO'#CfO#XOSO'#CiOOOO'#Cj'#CjO{OSO'#CkOOOO'#Ce'#CeOOOO'#Cd'#CdOOOO,58y,58yOOOO-E6r-E6rOOOO,58|,58|OOOO-E6s-E6sOOOO1G.f1G.fOOOO1G.t1G.tOOOO1G.w1G.wO#`OPO,59QOOOO'#Cv'#CvO#eOSO,59TOOOO,59T,59TO#lOSO'#C}O#tOSO,59VOOOO1G.l1G.lOOOO-E6t-E6tOOOO1G.o1G.oO{OSO'#CwO#yOSO,59iOOOO1G.q1G.qOOOO,59c,59cOOOO-E6u-E6u",
  stateData: "$R~OTPOVTO`SOcQOfROuSO~OlQP~PQOVXO`YOa]OtYO~OTPOZ`OmaOobOpcO~OlQX[QX~PQOVXO`YOajOtYO~OdkO~OglO~O[QP~PQOnpO~P{O[sO~OnuO~P{OrvOsqX~OsxO~OrvOsqa~O",
  goto: "#vrPPsy!UP!eP!i!y!]PP!]!]!]PP#RPP#RPP#Y#a#g#mPPPPP#sQWORm`UUOV`Q^QR_RYSOQRV`]dTXacovTZP[QfTQhXSnaoQqcRyv]eTXacovZSOQRV`SVO`RgVQ[PRi[QoaRtoQwqRzwRrc",
  nodeNames: "⚠ Document Markup MarkupItem Math MathStart MathItem CodeStart Code Expression CodeMarkup CodeMarkupStart CodeMarkupEnd Scope Ident Array LineComment MathEnd Bold BoldStart BoldEnd Italic ItalicStart ItalicEnd",
  maxTerm: 37,
  nodeProps: [
    ["closedBy", 5,"MathEnd",11,"CodeMarkupEnd",19,"BoldEnd",20,"BoldStart",22,"ItalicEnd",23,"ItalicStart"],
    ["openedBy", 12,"CodeMarkupStart",17,"MathStart"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "'n~RjOs!sst!ztu#Pux!sxy#Wyz#az{#j{|!s|}#s}!P!s!P!Q#|!Q!c!s!c!}$r!}#O%p#O#P%y#P#Q&c#Q#R!s#R#S&j#S#T!s#T#o$r#o#p'U#p#q!s#q#r'_#r;'S!s;'S;=`'h<%lO!sR!zOuPtQ~#POV~V#WOaQTTV#aOpSuPtQV#jOsSuPtQV#sOdScPtQV#|OrSuPtQ~$TPuPtQ!P!Q$W~$ZSOY$gZ;'S$g;'S;=`$l<%lO$g~$lO`~~$oP;=`<%l$gV${TuPoStQ}!O%[!Q![%[!c!}%[#R#S%[#T#o%[S%aToS}!O%[!Q![%[!c!}%[#R#S%[#T#o%[V%yOZSuPtQR&QSuPtQst!stu!sz{&^#R#S&^P&cOuPR&jO[PtQ_&uTgWfPoStQ}!O%[!Q![%[!c!}%[#R#S%[#T#o%[V'_OmSuPtQV'hOnSuPtQR'kP;=`<%l!s",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
