// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Document = 1,
  Markup = 2,
  MarkupContent = 3,
  Math = 4,
  Code = 5,
  Content = 6,
  Scope = 9,
  Array = 12;
