// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Document = 1,
  Markup = 2,
  MarkupContent = 3,
  Math = 4,
  Code = 6,
  Content = 7,
  Scope = 10,
  Array = 13;
