// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "$tOQOPOOO]OQO'#C`OOOO'#C_'#C_ObOSO'#C_OOOO'#Ck'#CkOpOPO'#C^QOOOOOO!ROPO,58zOQOPO'#CbO!WOSO'#CeObOSO'#ChOOOO'#Ca'#CaOOOO,58y,58yOOOO-E6i-E6iOOOO1G.f1G.fO!iOPO,58|OOOO'#Cl'#ClO!nOSO,59POOOO,59P,59PO#POSO'#CsO#XOSO,59SOOOO1G.h1G.hOOOO-E6j-E6jOOOO1G.k1G.kObOSO'#CmO#^OSO,59_OOOO1G.n1G.nOOOO,59X,59XOOOO-E6k-E6k",
  stateData:
    "#f~OcQOdPOfRO~OeVO~OVWOYXO]YOdPO~OcQOdPOfRObQXWQX~Od^O~OVWOYXOZbO]YOdPO~OWeO~OVWOYXOZgO]YOdPO~OhhO^gX~O^jO~OhhO^ga~O",
  goto: "!uhPPiot!QyPPyPPyPP!_!f!lPPPPP!rQUOR_WVSOTWUQOTWZZRXYahQ[RS`XaQcYRkhSTOWR]TQaXRfaQicRliRdY",
  nodeNames:
    "⚠ Document Markup MarkupContent Math Code Content [ ] Scope { } Array ( )",
  maxTerm: 24,
  nodeProps: [
    ["closedBy", 7, "]", 10, "}", 13, ")"],
    ["openedBy", 8, "[", 11, "{", 14, "("],
  ],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData:
    "$W~RcOs!^st!etu!lux!^xy!qyz!zz|!^|}#T}!}!^!}#O#^#O#P!^#P#Q#g#Q#o!^#o#p#n#p#q!^#q#r#w#r;'S!^;'S;=`$Q<%lO!^R!eOcPeQR!lOfPeQ~!qOd~V!zO]ScPeQV#TO^ScPeQV#^OhScPeQV#gOVScPeQR#nOWPeQV#wOYScPeQV$QOZScPeQR$TP;=`<%l!^",
  tokenizers: [0, 1, 2],
  topRules: { Document: [0, 1] },
  tokenPrec: 0,
});
