/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_typststate_free: (a: number, b: number) => void;
export const typststate_new: () => number;
export const typststate_pt: (a: number) => number;
export const typststate_setPt: (a: number, b: number) => void;
export const typststate_size: (a: number) => number;
export const typststate_setSize: (a: number, b: number) => void;
export const typststate_theme: (a: number) => number;
export const typststate_setTheme: (a: number, b: number) => void;
export const typststate_insertFile: (a: number, b: number, c: number, d: number, e: number) => number;
export const typststate_installPackage: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const typststate_installFont: (a: number, b: number, c: number) => void;
export const typststate_compile: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const typststate_click: (a: number, b: number, c: number) => any;
export const typststate_autocomplete: (a: number, b: number, c: number) => any;
export const typststate_resize: (a: number, b: number, c: number, d: number, e: number) => void;
export const typststate_renderPdf: (a: number, b: number) => any;
export const __wbg_packagefile_free: (a: number, b: number) => void;
export const packagefile_new: (a: number, b: number, c: number, d: number) => number;
export const __wbg_themecolors_free: (a: number, b: number) => void;
export const themecolors_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number) => number;
export const rgb_new: (a: number, b: number, c: number) => number;
export const rgb_toString: (a: number) => [number, number];
export const __wbg_fileid_free: (a: number, b: number) => void;
export const start: () => void;
export const __wbg_rgb_free: (a: number, b: number) => void;
export const qcms_profile_is_bogus: (a: number) => number;
export const qcms_white_point_sRGB: (a: number) => void;
export const qcms_profile_precache_output_transform: (a: number) => void;
export const qcms_transform_data_rgb_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgba_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_bgra_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgb_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgba_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_bgra_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_release: (a: number) => void;
export const qcms_enable_iccv4: () => void;
export const lut_interp_linear16: (a: number, b: number, c: number) => number;
export const lut_inverse_interp16: (a: number, b: number, c: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_3: WebAssembly.Table;
export const __externref_table_alloc: () => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
