#!/usr/bin/env bash

version=$1
sha256sum=$2

if [[ -z "$version" || -z "$sha256sum" ]]; then
    echo "Usage: $0 <version> <sha256sum>" >&2
    exit 1
fi

cat <<EOF
pkgname=mnemo
pkgver=$version
pkgrel=1
pkgdesc="Note-taking app designed to enhance the retention of information."
arch=('x86_64')
url="https://github.com/lemueldls/mnemo"
license=('MIT')
depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup' 'pango' 'webkit2gtk-4.1' 'openssl')
makedepends=('cargo' 'git' 'file' 'appmenu-gtk-module' 'libappindicator-gtk3' 'librsvg' 'base-devel' 'curl' 'wget' 'rustup' 'webkit2gtk-4.1') options=('!strip' '!emptydirs')
source=("\$pkgname-v\$pkgver.tar.gz::https://github.com/lemueldls/\$pkgname/archive/refs/tags/\$pkgname-v\$pkgver.tar.gz")
sha256sums=('$sha256sum')
_builddir="\$pkgname-\$pkgname-v\$pkgver/platform"
prepare() {
    cd "\$srcdir/\$_builddir" || exit 1
    export RUSTUP_TOOLCHAIN=stable
    rustup toolchain install \$RUSTUP_TOOLCHAIN --target wasm32-unknown-unknown --profile minimal --no-self-update
    cargo fetch --locked --target "\$(rustc -vV | sed -n 's/host: //p')"
    cargo fetch --locked --target wasm32-unknown-unknown
}
build() {
    cd "\$srcdir/\$_builddir" || exit 1
    # unfortunately LTOFLAGS -flto=auto set by /etc/makepkg.conf break linking as those are added to CFLAGS automatically
    # building will bail out with something like: undefined reference to 'ring_core_0_17_8_OPENSSL_ia32cap_P' when -flto=auto is set
    export CFLAGS="\${CFLAGS//-flto=auto//}"
    pnpm tauri build -b deb || true
}
check() {
    cd "\$srcdir/\$_builddir" || exit 1
    export RUSTUP_TOOLCHAIN=stable
    cargo test --locked --frozen --package=models
}
package() {
   # use the intermediate artifacts generated by the bundler for creating the .deb
    cd "\${srcdir}/\${_builddir}/target/release/bundle/deb/\${pkgname}_\${pkgver}_amd64/data" || exit 1
    install -Dm755 usr/bin/mnemo "\$pkgdir"/usr/bin/mnemo
    install -Dm644 usr/share/applications/mnemo.desktop "\$pkgdir"/usr/share/applications/mnemo.desktop
    install -Dm644 usr/share/icons/hicolor/128x128/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/128x128/apps/mnemo.png
    install -Dm644 usr/share/icons/hicolor/256x256@2/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/256x256@2/apps/mnemo.png
    install -Dm644 usr/share/icons/hicolor/32x32/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/32x32/apps/mnemo.png
    install -Dm644 usr/share/licenses/mnemo/LICENSE "\$pkgdir"/usr/share/licenses/mnemo/LICENSE
}
EOF
