#!/usr/bin/env bash

version=$1
sha256sum=$2

if [[ -z "$version" || -z "$sha256sum" ]]; then
    echo "Usage: $0 <version> <sha256sum>" >&2
    exit 1
fi

cat <<EOF
pkgname=mnemo
pkgver=$version
pkgrel=1
pkgdesc="Local-first note-taking app leveraging the Typst ecosystem."
arch=('x86_64')
url="https://github.com/lemueldls/mnemo"
license=('AGPL-3.0')
depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup' 'pango' 'webkit2gtk-4.1' 'openssl')
makedepends=('cargo' 'nodejs' 'pnpm' 'git' 'file' 'appmenu-gtk-module' 'libappindicator-gtk3' 'librsvg' 'base-devel' 'curl' 'wget' 'rustup' 'webkit2gtk-4.1') options=('!strip' '!emptydirs')
source=("mnemo-v\$pkgver.tar.gz::https://github.com/lemueldls/mnemo/archive/refs/tags/mnemo-v\$pkgver.tar.gz")
sha256sums=('$sha256sum')
_builddir="\$pkgname-\$pkgname-v\$pkgver/platform"
prepare() {
    cd "\$srcdir/\$_builddir" || exit 1
    export RUSTUP_TOOLCHAIN=stable
    rustup toolchain install \$RUSTUP_TOOLCHAIN --profile minimal --no-self-update
    cargo fetch --locked --target "\$(rustc -vV | sed -n 's/host: //p')"
    pnpm install
}
build() {
    cd "\$srcdir/\$_builddir" || exit 1
    # unfortunately LTOFLAGS -flto=auto set by /etc/makepkg.conf break linking as those are added to CFLAGS automatically
    # building will bail out with something like: undefined reference to 'ring_core_0_17_8_OPENSSL_ia32cap_P' when -flto=auto is set
    export CFLAGS="\${CFLAGS//-flto=auto//}"
    export NODE_OPTIONS=--max-old-space-size=8192
    export NUXT_PUBLIC_API_BASE_URL="https://mnemo.world"
    pnpm tauri build -b deb -c "\${srcdir}/\${_builddir}/tauri/tauri.package.conf.json"
}
package() {
    install -Dm755 "\${srcdir}/\${_builddir}/target/release/mnemo" "\$pkgdir"/usr/bin/mnemo
    # Explicitly strip only the binary; !strip in options prevents makepkg's auto-strip phase which also generates
    # a debug package, which is useless here, as the debug information only contains symbols and no debug info
    strip "\$pkgdir"/usr/bin/mnemo
    # use the intermediate artifacts generated by the bundler for creating the .deb
    cd "\${srcdir}/\${_builddir}/target/release/bundle/deb/Mnemo_\${pkgver}_amd64/data" || exit 1
    install -Dm755 usr/bin/mnemo "\$pkgdir"/usr/bin/mnemo
    install -Dm644 usr/share/applications/Mnemo.desktop "\$pkgdir"/usr/share/applications/Mnemo.desktop
    install -Dm644 usr/share/icons/hicolor/128x128/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/128x128/apps/mnemo.png
    install -Dm644 usr/share/icons/hicolor/256x256@2/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/256x256@2/apps/mnemo.png
    install -Dm644 usr/share/icons/hicolor/32x32/apps/mnemo.png "\$pkgdir"/usr/share/icons/hicolor/32x32/apps/mnemo.png
    install -Dm644 usr/share/licenses/mnemo/LICENSE "\$pkgdir"/usr/share/licenses/mnemo/LICENSE
}
EOF
