// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states: "UQOOOOO",
  stateData: "Q~O",
  goto: "QPP",
  nodeNames: "⚠ Program",
  maxTerm: 2,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "RORO",
  tokenizers: [],
  topRules: { Program: [0, 1] },
  tokenPrec: 0,
});
