name: "📱"

on:
  release:
    types:
      - published

jobs:
  publish:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      publish: true
