name: "📱 Android (push)"

on:
  push:
    branches:
      - main
      - dev

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point sG,omething broke.
  group: ${{ github.ref == 'refs/heads/main' && format('android-main-{0}', github.sha) || format('android-{0}', github.ref) }}

jobs:
  push:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
