name: Nix Derivations

on:
  release:
    types: [released]
  workflow_call:
  workflow_dispatch:

jobs:
  update-nix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: 🏷️ Get release info
        id: release-info
        uses: ./.github/actions/latest-release-info

      - name: ⚙️ Setup SSH signing key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global gpg.format ssh
          git config --global user.signingKey ~/.ssh/id_ed25519
          git config --global user.name "Lemuel DLS"
          git config --global user.email "noreply@git.lemueldls.dev"

      - name: ❄️ Install nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: 🔄 Update nix flake
        run: |
          nix run nixpkgs#nix-update -- --flake --version "${{ steps.release-info.outputs.tag }}" mnemo
          nix run nixpkgs#nix-update -- --flake --version "${{ steps.release-info.outputs.tag }}" mnemo-bin

      - name: 💾🏷️⬆️ Commit and push
        run: |
          git add -A
          git commit -S -m "chore: update nix flake" || echo "No changes to commit"
          git push
